#! /bin/bash
# Shell script to set the environment variables for SGA project.

project=SGA

#############################
# For a power-user / testing.
export LEGACYPIPE_CODE_DIR=/global/homes/i/ioannis/repos/git/legacypipe
export PYTHONPATH=$LEGACYPIPE_CODE_DIR/py:$PYTHONPATH
#############################

# Specifiy the location of the input and output data.
export LEGACYHALOS_DIR=/global/cfs/cdirs/desi/users/ioannis/$project
export LEGACYHALOS_DATA_DIR=/global/cscratch1/sd/ioannis/SGA-lg9-data # hack
export LEGACYHALOS_HTML_DIR=/global/cfs/cdirs/cosmo/www/temp/ioannis/SGA-lg9-html # hack

# Use a local checkout of the code even though it's in the Docker container.
export LEGACYHALOS_CODE_DIR=/global/homes/i/ioannis/repos/git/legacyhalos
export PATH=$LEGACYHALOS_CODE_DIR/bin/SGA:$PATH # hack!
export PYTHONPATH=$LEGACYHALOS_CODE_DIR/py:$PYTHONPATH

# Pipeline variables---only change these if you know what you're doing!
export LEGACY_SURVEY_DIR=/global/cfs/cdirs/cosmo/work/legacysurvey/lg9
export GAIA_CAT_VER=2
export GAIA_CAT_DIR=/global/cfs/cdirs/cosmo/work/gaia/chunks-gaia-dr2-astrom-2
export UNWISE_COADDS_DIR=/global/cfs/cdirs/cosmo/data/unwise/neo6/unwise-coadds/fulldepth:/global/cfs/cdirs/cosmo/data/unwise/allwise/unwise-coadds/fulldepth
export UNWISE_MODEL_SKY_DIR=/global/cfs/cdirs/cosmo/work/wise/unwise_catalog/dr3/mod
export SKY_TEMPLATE_DIR=/global/cfs/cdirs/cosmo/work/legacysurvey/dr9k/calib/sky_pattern
export TYCHO2_KD_DIR=/global/cfs/cdirs/cosmo/staging/tycho2
export LARGEGALAXIES_CAT=/global/cfs/cdirs/cosmo/staging/largegalaxies/v3.0/SGA-parent-v3.0.kd.fits
export PS1CAT_DIR=/global/cfs/cdirs/cosmo/work/ps1/cats/chunks-qz-star-v3
export DUST_DIR=/global/cfs/cdirs/cosmo/data/dust/v0_1
export GALEX_DIR=/global/cfs/cdirs/cosmo/data/galex/images
# Uncomment this variable if you want time-resolved unWISE photometry (generally not needed). 
#export UNWISE_COADDS_TIMERESOLVED_DIR=/global/cfs/cdirs/cosmo/work/wise/outputs/merge/neo6

export PYTHONNOUSERSITE=1
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export KMP_AFFINITY=disabled
export MPICH_GNI_FORK_MODE=FULLCOPY
